version: '3.1'

services:

  backend:
    image: asjordi/backend-urlshortjs:1.0.0
    container_name: backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - ENV=${ENV}
      - URL=${URL}
      - PORT=${PORT}
    networks:
      - urlshort

  frontend:
    image: asjordi/frontend-urlshortjs:1.0.0
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - urlshort

networks:
  urlshort:
    driver: bridge
